### PR TITLE
1.8/14w08a block update patch

### PR DESCRIPTION
**Pull request by Khroki**
Updated minecraft.yaml /materials.py in preperation for 1.8, See my other pull request for the matching terrain.png

### CODE REVIEW

**Comment by Khroki** [comment]
oh, sorry forgot to mention, I only did the ones for the main minecraft, wasn't sure what was involved in changing the pocket and classic versions.

**Comment by Lechros** [comment]
Because I rewrited every texture (x,x) thing in pocket.yaml with mcpe's terrain.png(32 blocks size) and now I have to do it all over again...

**Comment by Khroki** [comment]
Pocket uses a seperate terrain.png, so shouldn't conflict.

**Comment by Lechros** [comment]
Oh that's very very nice!!!

**Comment by Lechros** [comment]
Hey what about other block's data so that they are like this?:
1:
  name: Im up
  tex: Im down
I saw you did this in double stone slab(maybe) but all other things you skipped.

**Comment by Khroki** [comment]
Basically if I skipped something it was because I didn't need to add it, and this is more efficient than adding every side individually. you seemed to use a similar approach to the double slabs, so not sure 100% on the question, but I can explain my doubleslab entries, double sandstone slab is expressed as:
      1:
        name: Double Sandstone Slab
        tex: [0, 12]        <- main texture for this block
        tex_direction:
          TOP: [0, 11]    <- override for top side of block, so it uses a different texture
          BOTTOM: [0, 13]   <- override for bottom side of block
the tex: entry is the default texture for the block and textures all 6 sides with it, the tex_direction works as an override as stated above to change the appropriate textures.
The later doubleslab entries, like netherbrick slabs, look the same on all sides so they don't need all the information that stone/sandstone doubleslabs need:
      6:
        name: Double Nether Brick Slab
        tex: [0, 14]
if tex isn't specified at all, it uses the entry before the data section, really the data entries are to override whatever was entered before the data section and to add damage values to the block list. The entries for logs (id 17) may make more sense. 

I did accidentally leave too much in the first stone slab entry, submitted a new pull request fixing most of the stuff I noticed including a missing slime-block texture.

**Comment by Lechros** [comment]
I mean you put name: up and tex: down but some you didnt and it kills my ocd
good:
name: blah
tex: [h,h]

bad:
tex: [bl,ah]
name: asdf

**Comment by Khroki** [comment]
Oh lol, yeah it was like that before I made my edits and I didn't bother spending the effort redoing all the misordered entries. Something like a third of them were like that. I corrected a few until I realized how many were out of order.

**Pull request closed without merging**
