### PR TITLE
Change Locked Chest to Stained Glass.

### PR DESCRIPTION
**Pull request by ZeroErrors**
Change the locked chest item to stained glass.
Mainly to make relighting chunks correctly for 1.7

### CODE REVIEW

**Comment by WetDesertRock** [comment]
This seems like the wrong kind of fix for the issue. Why would you have to change the name? This effects scripts that may try to get the common name from the id, or visa-versa. Would just adding `type: GLASS` to the Locked Chest fix it?

**Comment by ZeroErrors** [comment]
That's a fair point, The name should stay the same then.
I'm not sure what needs to be changed just for the lighting I did not get time to look into it in depth.
I also set the `opacity: 0` setting, it looks to be what controls part of the lighting as ice has an `opacity: 3` set.

**Comment by orphu** [comment]
But, stained glass replaced locked chest in 1.7. Leaving named locked chest is incompatible.

**Comment by WetDesertRock** [comment]
Oh, this is true. Seems like the first commit is the fix then. My bad.

**Comment by Khroki** [comment]
This has been fixed with the newest commits, so there you are :D.

**Pull request closed without merging**
