### PR TITLE
Added `box.positions`, to complement `box.chunkPositions`.

### PR DESCRIPTION
**Pull request by eric-wieser**
This seems to be a very common use of the box class, so I feel this should be in the library:

``` python
for x, y, z in box.positions:
    if level.blockAt(x, y, z) == theBlock:
        level.setBlockAt(x, y, z, theOtherBlock)
```

### CODE REVIEW

**Comment by eric-wieser** [comment]
This could possibly be rewritten as `__iter__` allowing the code to be further simplified to:

``` python
for x, y, z in box:
    if level.blockAt(x, y, z) == theBlock:
        level.setBlockAt(x, y, z, theOtherBlock)
```

**Comment by eric-wieser** [comment]
[Approved by Sethbling](http://www.reddit.com/r/Minecraft/comments/u7kto/i_wrote_an_mcedit_filter_that_will_turn_chests_of/c4t07a0)

**Comment by TkTech** [comment]
Looks alright, but that particular example would be much, much faster if the compare-and-change was pushed down into C using numpy. `newArray[oldArray==theBlock] = theOtherBlock`.

**Comment by eric-wieser** [comment]
I do not understand that example at all (having never used numpy). Does that read "set the entries in newArray where the index of the old array contained `theBlock` to theOtherBlock"?

Also, what about more complex operations on each element (rather than a simple replacement)?

**Comment by TkTech** [comment]
That is indeed how it reads. More complex operations require more complex solutions :)

There are many cases where common operations (such as replacing all blocks of a type in a chunk) could be much improved.

**Comment by TkTech** [comment]
(Woops, wrong button).

**Comment by eric-wieser** [comment]
So are you gonna merge this then? It's still faster than what I've seen a lot of people write:

``` python
for x in range(box.minx, box.maxx):
    for y in range(box.miny, box.maxy):
        for z in range(box.minz, box.maxz):
           foo(x, y, z)
```

**Comment by TkTech** [comment]
Don't have access to my machine at the moment to clean it :) It's missing a docstring, and doesn't meet PEP8 (namely > 80 chars). I also can't just merge in code (regardless of how simple) without testing it.

**Comment by eric-wieser** [comment]
There you go. Just needs testing now. That entire file is pretty docstringless

**Pull request merged**
