### PR TITLE
Absolutely perfect update for 0.8.0

### PR DESCRIPTION
**Pull request by Lechros**
I will add new 32*16 terrain.png file later

### CODE REVIEW

**Comment by Lechros** [comment]
Please use the Best update ever! I hope it's not like nope we delete this thing becuz this is my first time updating commits(?)

**Comment by codewarrior0** [comment]
Thanks for the update!

FYI, the "aka" field is for extra search words. You don't have to put a word in the "aka" if it's already in the "name" field.

**Comment by codewarrior0** [comment]
Seems like a lot of texture coordinates are wrong. I'm reverting this change. Hope you can send a working update soon.

pocket graphics bug

**Comment by Lechros** [comment]
Can you check if the image file size is ok?

**Comment by Lechros** [comment]
I didnt update pocket terrain.png itself or block numbers for it

**Comment by Lechros** [comment]
Sry for spamming but does terrain.png have to be square? it is 512*256

**Comment by codewarrior0** [comment]
Judging by the skewed proportions in the picture above: Yes.

**Comment by Lechros** [comment]
I will give you the square version of terrain.png file tomorrow pls dont delete my update and jusy wait 1 day please

**Comment by codewarrior0** [comment]
I hope you are going to test your changes this time.

**Comment by Lechros** [comment]
https://www.dropbox.com/s/ijj7uo44pssc9bb/terrain.png
Heres new 512*512 terrain.png and (how do i test my changes!)

**Comment by codewarrior0** [comment]
To test your changes, you can either run MCEdit from source code (directions are here: https://github.com/mcedit/mcedit) or you can insert your `terrain-pocket.png` and `pocket.yaml` files into the correct places in the MCEdit folder. 

`terrain-pocket.png` goes into the `MCEdit-0.1.7-blahblahblah` folder. 

`pocket.yaml` goes into the `library.zip` file inside that folder, inside the `pymclevel` folder that's inside the `library.zip`

files

**Comment by Lechros** [comment]
Does the new terrain.png file work??

**Comment by Khroki** [comment]
Since I found the running from source guide more complicated than necessary here's a simpler way for windows. I couldn't get easy_install to work anyway.

Download both the mcedit and pymclevel repositories, put the pymclevel repository in a subfolder in the mcedit repository, like this:
untitled

Download and install Python2.7, PyOpenGL, numpy, pygame, pyyaml install files, there are installers for all of these available at the following locations:
http://www.python.org/download/releases/2.7/
https://pypi.python.org/pypi/PyOpenGL/3.0.2
http://sourceforge.net/projects/numpy/files/NumPy/
http://www.pygame.org/download.shtml
http://pyyaml.org/wiki/PyYAML
If you're given the option of 32bit or 64bit, 32 is a safer bet.
Assuming all of this is installed correctly, you might be able to just doubleclick mcedit.py to start mcedit.

If it won't start due to file associations or whatnot, or you just want to see console output you can try a batch file. A simple .bat file in the mcedit root folder to start mcedit will do the job, mine looks like this: 
C:\python27\python.exe mcedit.py
Pause <-optional, keeps the window open if it crashes.

Batch files are made by renaming .txt files to .bat.

Once you have it working, just replace the appropriate files with your updated version, I found copy pasting the contents from github's editor into the file opened in notepad works fine for this.

**Comment by Lechros** [comment]
Wow thats so complicated for normal people like me

**Comment by Khroki** [comment]
Well, you still can just copy paste your edits into a compiled version, like the newest dev version, you'll have to put the pocket.yaml in the library zip under the pymclevels folder though, codewarrior has instructions for that above.

**Comment by Lechros** [comment]
Yeah now I dont have to update it in github

**Pull request merged**
