### PR TITLE
Minecraft.yaml 1.8 general fixes

### PR DESCRIPTION
**Pull request by Khroki**
Fixed typos and a few redundant lines, added Primed TNT and slime block texture, and fixed some incorrect textures. Needs updated terrain.png, see other pull request.

### CODE REVIEW

**Comment by codewarrior0** [comment]
Thanks for the update!

**Comment by Khroki** [comment]
You're welcome, don't forget the other pull request with terrain.png.

**Comment by Lechros** [comment]
mcedit automatically make upside down half slabs right? I copied map from pc to pe and all of upside down spruce wood slabs changed to normal oak wood slabs.

**Comment by codewarrior0** [comment]
When you copy from PC to PE, it uses the block name to figure out what the new ID is. Make sure you use the same name as PC to make it convert correctly. In the future, Minecraft's internal names will be used instead.

**Comment by Khroki** [comment]
Yeah, I've edited quite a few block names to make them more consistent or to update them to more current MC versions, so that may be your problem. I updated minecraft.yaml to use the new block id naming system already. Should I update classic.yaml to the same system for compatibility?

**Comment by Lechros** [comment]
Well, who cares about classic?

**Comment by dratini0** [comment]
We should either drop classic support entirely, or maintain it. I think we
shouldn't have something broken.

**Comment by Lechros** [comment]
I dont know much about classic but do they even have upside down slabs? or even just slabs?

**Comment by dratini0** [comment]
It has the standard old smooth stone slab.

**Comment by Khroki** [comment]
Well, slabs or not future blocks won't have id numbers, so adding the current minecraft PC idstr and block name to classic.yaml, pocket.yaml, etc, might be a good idea depending on how the new system is implemented. I don't really fully understand the system as it stands tbh and was wondering if I should bother doing it.

**Comment by Khroki** [comment]
Oh and expect another update to minecraft.yaml to add better support for rotatable blocks, such as being able to place chests in specific directions, the current tex_direction_data: {2: NORTH, 3: SOUTH, 4: WEST, 5: EAST} system is completely broken as is. We may need some system to properly rotate blocks in the future though. Like a hotkey that increments the damage value for certain blocks within a given range of damage values.

**Comment by Lechros** [comment]
okay. more and more works. maybe i should just use current version

**Comment by Khroki** [comment]
The names aren't going to change, so it should be fine to update based on the current version

**Comment by Lechros** [comment]
Its not gonna be like spruce upside down half slab or upside down dark oak planks (north)? lol

**Comment by Khroki** [comment]
I'm not sure if I'm going to touch stairs, but dispensers/chests/droppers etc there's not much other choice as long as there's currently no way to rotate individual blocks, I say continue on the current version, we can always fix glitches later. Here's how stuff looks so far, about half what's shown matches what it looks like in game. 
testworld
Adding the rotations to the block list should provide better building control. Also there's a chance I might add the upside down slabs, for convenience, but I won't rename the normal ones.

I know it's frustrating, but honestly minecraft.yaml was in a state of pretty bad neglect, it takes a while to get everything working right.

**Comment by Khroki** [comment]
I am looking forward to the idStr change though, that'll fix this whole needing to coordinate names thing.

**Comment by Lechros** [comment]
I will add stained glass and double tall plants(this exist?) and ender chest texture stuff if you want

**Comment by Lechros** [comment]
What does IdStr stands for?

**Comment by Khroki** [comment]
the stained glass has a placeholder texture since partial transperency isn't supported so that shouldn't be needed, and the tall plant tops are dynamically assigned and therefore impossible to set manually. But a good enderchest texture that's the same size as the old chest texture would be much appreciated. The real ender chest texture is a bit too small.

idStr is idstring, like coal_block for coal block.

**Comment by Lechros** [comment]
idStr is mcedit only thing? Not from like MC game code?

**Comment by Khroki** [comment]
well, my understanding is the idStr is supposed to match the new mc 1.8 name id system that is supposed to replace id numbers.

**Comment by Khroki** [comment]
so if you want some orange carpet, instead of using 171:1 you use carpet:1, and by adding the idStr to files like pocket.yaml it'll allow it to convert between formats without having exactly the same name.

**Comment by codewarrior0** [comment]
ID strings won't be used in MCEdit until they are stored in Minecraft's save files. They won't be stored in the save files until the data field is deprecated, which means you won't ever see carpet:1 because new ID strings will be added for the different types of carpet, wood, colored glass, and so on.

**Comment by Khroki** [comment]
ah ok then, I wasn't completely sure, good to know and when that happens I guess I'll update it then :P I was just going on the current 1.8 snapshot behavior. which to get an orange carpet, you use /give [name] carpet [quantity] 1

**Comment by Khroki** [comment]
Also codewarrior, what's your opinion on my method of adding proper chest rotations? currently I'm adding entries for all rotations so they can be selected in mcedit, or are there plans to add a rotate block feature?

**Comment by codewarrior0** [comment]
With MCEdit 2.0 on the horizon, the only changes to MCEdit 0.x will be updated block definitions.

**Comment by Lechros** [comment]
https://www.dropbox.com/s/ijj7uo44pssc9bb/terrain.png
Perfected terrain.png
Remade ender chest texture, supposed-to-be trapped chest texture, supposed-to-be silverfish rocks texture, updated lava/water texture, and added new sapling types

**Comment by Khroki** [comment]
Ok, fair enough, I'll just keep adding block rotations this way for now then, since I assume it'll be quite a while before 2.0 is ready. Btw, is there somewhere I have to define transparent blocks so they don't put holes in the world? like the hoppers in the above screenshot or barrier blocks?

**Comment by Lechros** [comment]
When will the 2.0 come out? My computer absolutely sucks and can I still get over 0.5fps? I have bad grapics not enough to run MC.

**Comment by Khroki** [comment]
Should get optifine onioni if you don't have it, makes a big difference on low end pcs. Anyway, you seem to have an old terrain.png, no matter, I'll merge it with mine and upload when I'm done adding rotations, I like the more subtle trapped chest especially.

**Comment by Lechros** [comment]
I had fun making it as a texture pack maker. And btw Minecraft doesnt even launch on my pc :(
Is there way to add block shapes? I worked on ModPE Scripts for PE and I know how to use defineblockshape thing but I dont know if mcedit is same

**Comment by Khroki** [comment]
No idea tbh, also if you want to make another texture, I need a hopper side output texture so I can set it's rotations. going to leave the black border around those lower stone textures btw, they're there to differentiate silverfish blocks from ordinary stone.
If you want to discuss this somewhere else, my steam name is simple physics.

**Comment by Lechros** [comment]
Can you send me the minecraft.yaml code when it is finished? I want to update pocket.yaml before codewarrior release anything, and make it more compatible

**Comment by Khroki** [comment]
Sure, prob be a few hrs though.

**Comment by Khroki** [comment]
New, and likely final 1.8 minecraft.yaml. https://github.com/Khroki/pymclevel/blob/master/minecraft.yaml
Edit: Committed, I don't plan to do anymore updates to this file for 1.8 so you should be safe now Oni.

**Pull request merged**
