### PR TITLE
Support dimensions with arbitrary directory names.

### PR DESCRIPTION
**Pull request by philippelatulippe**
With this patch, dimension directories no longer have to be in the format "DIM-_n_".  

To the best of my knowledge, this should have no backward-compatibility effect for programs that use this library, with one exception:  applications that access `MCInfdevOldLevel`'s `dimensions` hash instead of calling `getDimension()`.  This is because `dimensions`'s key was the dimNo of a dimension, which may not be a meaningful number for worlds that do not follow the "DIM-_n_" format.  The key is now the name of the dimension's directory.

For the mcedit counterpart of this patch, see https://github.com/mcedit/mcedit/issues/122

### CODE REVIEW

**Comment by TkTech** [comment]
Giving a two day period for existing users to comment before merging.

**Comment by codewarrior0** [comment]
Why is this needed? Does Minecraft officially support named dimensions now?

**Comment by TkTech** [comment]
Nein, it's primarily for bukkit servers I believe, but there might be other use cases.

**Comment by philippelatulippe** [comment]
Personally, I used it to edit worlds generated with MystCraft (http://binarymage.com).  Has there been any trouble with the change?

**Comment by TkTech** [comment]
I haven't seen any as of yet with 10000+ downloads of the version including it. There were a few for people running from source, but they did not understand that you had to update the submodules, so EBKAC.

**Comment by codewarrior0** [comment]
What is done with the "Dimension" field in the player's TAG_Compound? It is an integer field in vanilla, so named dimensions won't fit. MystCraft seems to use numbered dimensions internally.

This patch breaks the ability to send players to other dimensions using the Move Player feature, and adds confusing repeated entries to the Goto Dimension menu.

**Pull request merged**
