### PR TITLE
Add PyPI compatibility

### PR DESCRIPTION
**Pull request by sixohsix**
- moved py files to a pymclevel package
- added setup.py and setup.cfg files
- added mce.py as a command-line script in setup.py
- changed some paths in tests.py and run_regression_test.py
- removed whitespace in mce.py (my editor did it of its own volition! sorry!)

### CODE REVIEW

**Comment by sixohsix** [comment]
This would close Issue 17.

**Comment by codewarrior0** [comment]
Hey, thanks for this! I'm not sure if pymclevel is ready for inclusion in the package index, but thanks to you it won't take much work. I'll merge this in as soon as I can.

**Comment by sixohsix** [comment]
After using pymclevel to build a map-modifying script, I can assure you that it's ready for PyPI. It's solid code with a great API. It's exactly what I want from a mc map tool.

**Comment by codewarrior0** [comment]
Merged, with a change so I could keep the same folder structure.

**Pull request closed without merging**
