### PR TITLE
Final 1.8 Minecraft.yaml Update

### PR DESCRIPTION
**Pull request by Khroki**
Fixes cauldrons, added rotations for common blocks, added enderchest bottom. Unless new blocks are added to 1.8, this should be the last update for now.

### CODE REVIEW

**Comment by Lechros** [comment]
One thing I would do is add cauldron bottom texture that actually looks right. Who cares if it make Xray machine?

**Comment by Khroki** [comment]
Tbh I wasn't too concerned with it since it's pretty rare for someone to see the bottom of a cauldron in the first place.

**Comment by Khroki** [comment]
and at least this way you can tell it's there if you're underneath it, the bottom cauldron texture is only like 12 pixels

**Comment by Lechros** [comment]
This will be the final update of mcedit for now, and I saw some missed/unnessesary enters and 2 tex-s for furnace in this commit. Fix it before codewarrior merge it!

**Comment by Lechros** [comment]
I mean chest not furnace

**Comment by Khroki** [comment]
Ah, figured I'd miss something, removed 2 extra line breaks and the double texture definition on chests.

**Pull request merged**
