### PR TITLE
"compressed" option for nbt.load()

### PR DESCRIPTION
**Pull request by orphu**
nbt.load() seems to have trouble with non-compressed nbt files. (Try loading data/idcounts.dat, for example). This adds a compressed option to load() much like the same option for save() that forces compression off.

### CODE REVIEW

**Comment by codewarrior0** [comment]
This is what try_gunzip is for. Do you have an error log that shows it isn't working?

**Comment by orphu** [comment]
I've had cases where certain idcounts.dat files seem to fail the try_gunzip check. Creating my own buffer and bypassing the gunzip step seems to load these files just fine. For example, when map == 3 seems to be one:

```
>>> import nbt
>>> f1 = nbt.load("idcounts.dat")
>>> f1
<TAG_Compound name='' keys=[u'map']>
>>> f1['map'].value
35
>>> f2 = nbt.load("idcounts2.dat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nbt.py", line 518, in load
    return _load_buffer(try_gunzip(buf))
  File "nbt.py", line 531, in _load_buffer
    raise NBTFormatError("Asked to load root tag of zero length")
nbt.NBTFormatError: Asked to load root tag of zero length
>>> h = file("idcounts2.dat", "rb")
>>> f2 = nbt._load_buffer(h.read())
>>> f2
<TAG_Compound name='' keys=[u'map']>
>>> f2['map'].value
3
```

**Comment by codewarrior0** [comment]
I just took a look at a villages.dat that had the same problem. It looks like the hacky workaround in gunzip() is only there to load worlds made by the Primordial Desert generator (and probably other generators from the same author). I'm going to switch it back to using gzip.GzipFile and try to figure out what's going on with Primordial Desert later.

**Comment by codewarrior0** [comment]
By the way, "print f2" should pretty-print the tag for you.

**Comment by orphu** [comment]
Pretty! 

```
>>> import nbt

>>> print nbt.load("idcounts.dat")
TAG_Compound({
  "map": TAG_Short(35),
})

>>> print nbt.load("idcounts2.dat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nbt.py", line 518, in load
    return _load_buffer(try_gunzip(buf))
  File "nbt.py", line 531, in _load_buffer
    raise NBTFormatError("Asked to load root tag of zero length")
nbt.NBTFormatError: Asked to load root tag of zero length

>>> print nbt._load_buffer(file("idcounts2.dat", "rb").read())
TAG_Compound({
  "map": TAG_Short(3),
})
```

Sounds good to me, although I'm SURE people will complain about not being able to read Primordial Desert maps again.

**Comment by orphu** [comment]
Reverting back to gzip.GzipFile seems to have fixed this. I'll close out the pull request.

**Pull request closed without merging**
