### PR TITLE
Fixes for Anvil memory leak and UTF-8 coding in sign text

### PR DESCRIPTION
**Pull request by dcoshea**
This branch contains a fix for the "Extreme Memory Leak/Usage In Various Operations" issue for Anvil (mcedit/pymclevel#93, commit 4378e6a) plus two small fixes to the exception handling that is invoked when we run out of memory, and a fix for handling of signs that have UTF-8 characters in them.

### CODE REVIEW

**Comment by TkTech** [comment]
Just as an update, a build including this is available for 64bit Windows (XP SP3+) on the downloads page as TESTING, and is merged into the dev branch. This pull request will be accepted when testing is complete.

**Comment by dcoshea** [comment]
@TkTech Thanks!  Are those test builds announced somewhere like minecraftforum.net?

**Comment by TkTech** [comment]
@dcoshea http://w.tkte.ch/projects/mcedit under the testing column.

**Comment by dcoshea** [comment]
@TkTech Thanks!

**Pull request merged**
